# Generated by Django 5.1.4 on 2025-01-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('issue_number', models.IntegerField()),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
