# Generated by Django 5.1.4 on 2025-01-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comicbook_page_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance_type', models.CharField(choices=[('main', 'Main Role'), ('cameo', 'Cameo'), ('first', 'First Appearance')], default='main', max_length=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.character')),
                ('comic_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.comicbook')),
            ],
        ),
    ]
