# Generated by Django 5.1.4 on 2025-01-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_character_characterappearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='comic_book',
            field=models.ManyToManyField(to='main_app.comicbook'),
        ),
    ]
