# Generated by Django 5.1.4 on 2025-01-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_character_comic_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='comic_book',
            new_name='comic_books',
        ),
    ]
